- name: TOKYO MX
  type: GR
  channel: "16"
  isDisabled: false
- name: フジテレビ
  type: GR
  channel: "21"
  isDisabled: false
- name: TBS
  type: GR
  channel: "22"
  isDisabled: false
- name: テレ東
  type: GR
  channel: "23"
  isDisabled: false
- name: テレビ朝日
  type: GR
  channel: "24"
  isDisabled: false
- name: 日テレ
  type: GR
  channel: "25"
  isDisabled: false
- name: NHK Eテレ
  type: GR
  channel: "26"
  isDisabled: false
- name: NHK総合
  type: GR
  channel: "27"
  isDisabled: false
- name: NHK BS
  type: BS
  channel: BS15_0
  serviceId: 101
- name: BS日テレ
  type: BS
  channel: BS13_0
  serviceId: 141
- name: BS朝日
  type: BS
  channel: BS01_0
  serviceId: 151
- name: BS-TBS
  type: BS
  channel: BS01_1
  serviceId: 161
- name: BSテレ東
  type: BS
  channel: BS01_2
  serviceId: 171
- name: BSフジ
  type: BS
  channel: BS13_1
  serviceId: 181
- name: BS11イレブン
  type: BS
  channel: BS09_0
  serviceId: 211
- name: BS12トゥエルビ(TwellV)
  type: BS
  channel: BS09_2
  isDisabled: false
  serviceId: 222
- name: 放送大学 BS1
  type: BS
  channel: BS11_0
  isDisabled: false
  serviceId: 231
- name: 放送大学 BS2
  type: BS
  channel: BS11_0
  isDisabled: false
  serviceId: 232
- name: BS松竹東急
  type: BS
  channel: BS23_3
  isDisabled: false
  serviceId: 260
- name: BSJapanext
  type: BS
  channel: BS23_2
  isDisabled: false
  serviceId: 263
- name: BSよしもと
  type: BS
  channel: BS23_1
  isDisabled: false
  serviceId: 265
